"""Image model

Revision ID: 673731c7a779
Revises: ecb32dc67ea1
Create Date: 2020-03-08 18:00:03.127580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673731c7a779'
down_revision = 'ecb32dc67ea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
