"""Add status, created, updated columns

Revision ID: ecb32dc67ea1
Revises: 808280c4a0d3
Create Date: 2020-01-29 15:18:41.277951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb32dc67ea1'
down_revision = '808280c4a0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wish', sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('wish', sa.Column('status', sa.String(), nullable=False))
    op.add_column('wish', sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wish', 'updated')
    op.drop_column('wish', 'status')
    op.drop_column('wish', 'created')
    # ### end Alembic commands ###
